name: Android Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: gigcredit_app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Configure Gradle
        run: |
          echo "org.gradle.jvmargs=-Xmx2048M -XX:MaxMetaspaceSize=512M" >> android/gradle.properties
          echo "org.gradle.parallel=false" >> android/gradle.properties

      - name: Build APK
        run: flutter build apk --release --split-per-abi --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: gigcredit_app/build/app/outputs/flutter-apk/*.apk
